### ISSUE TITLE
HPP Additional Fields

### ISSUE THREAD

**Issue by steve-ico3** [globalpayments/php-sdk#109]
Hi,

I'm looking to send additional fields to the HPP

https://developer.globalpay.com/ecommerce/hosted-solution/hpp-address-capture#hpp-additional-fields

But I can't see any way to do this via the SDK, am I missing it or is this functionality not there?

I can see the form example on that page but I can't see a way do achieve the same thing via the SDK, 

I'm using the latest version (5.0.0)

**Comment by cristina-nechita** [comment]
Hi, 

You can set on HostedPaymentData object "addressCapture" for "HPP_CAPTURE_ADDRESS" and  "notReturnAddress" for "HPP_DO_NOT_RETURN_ADDRESS".

**Comment by steve-ico3** [comment]
Thank you
