### ISSUE TITLE
Possible incorrect order of parameters in call to generateHash

### ISSUE THREAD

**Issue by damiencarbery** [globalpayments/php-sdk#11]
In src/Gateways/RealexConnector.php line 974 GenerationUtils::generateHash() is called but the parameters appear to be the wrong order.
https://github.com/globalpayments/php-sdk/blob/master/src/Gateways/RealexConnector.php#L974

```
return GenerationUtils::generateHash(
            implode('.', $data),
            $this->sharedSecret
        );
``` 

The definition of GenerationUtils::generateHash() has the $secret being the first parameter:
`public static function generateHash($secret, $toHash = null)`
https://github.com/globalpayments/php-sdk/blob/master/src/Utils/GenerationUtils.php#L68

**Comment by eric-vest** [comment]
Hi Damien,

Thanks for pointing this out, we'll work on getting this fixed in our next update.

**Comment by mcspronko** [comment]
Hi,

Is there any update on the issue? It seems like the authorize, verify and charge commands do not work due to the incorrect hash. As a result the 506 error is shown when we try to render an iframe.

Thanks.

**Comment by eric-vest** [comment]
Hi guys,

Sorry for the delay.  I'll get this updated right away and try to have it pushed out by Tuesday.  I'll let you know when it's completed.

**Comment by eric-vest** [comment]
Hey, this issue has been corrected in the newest version of the SDK.  Check it out and let us know if you have any issues with it.

Thanks.
