### ISSUE TITLE
Credit card charge execution error "Unexpected HTTP status code [0]"

### ISSUE THREAD

**Issue by alecogt** [globalpayments/php-sdk#12]
I am trying to charge a credit card as described at https://developer.heartlandpaymentsystems.com/Ecommerce/Card. It works properly on localhost but not on our server. I am receiving the following error:
"GlobalPayments\\Api\\Entities\\Exceptions\\GatewayException(code: 0): Unexpected HTTP status code [0] at globalpayments/php-sdk/src/Gateways/XmlGateway.php:25"

Digging deeper I found that the error comes from the file globalpayments/php-sdk/src/Gateways/Gateway.php in the sendRequest function on this line:
`$curlResponse = curl_exec($request);`
The error I see with `curl_error($request);` is `Unknown cipher in list: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES12`

If I comment out the following lines the transaction succeeds:
`$supportedCiphers = [
                'ECDHE-ECDSA-AES256-GCM-SHA384',
                'ECDHE-RSA-AES256-GCM-SHA384',
                'ECDHE-ECDSA-AES256-SHA384',
                'ECDHE-RSA-AES256-SHA384',
                'ECDHE-ECDSA-CHACHA20-POLY1305',
                'ECDHE-RSA-CHACHA20-POLY1305',
                'DHE-RSA-AES256-GCM-SHA384',
                'DHE-RSA-AES256-SHA256',
                'ECDHE-ECDSA-AES128-GCM-SHA256',
                'ECDHE-RSA-AES128-GCM-SHA256',
                'ECDHE-ECDSA-AES128-SHA256',
                'ECDHE-RSA-AES128-SHA256',
                'DHE-RSA-AES128-GCM-SHA256',
                'DHE-RSA-AES128-SHA256'
            ];`
and
`curl_setopt($request, CURLOPT_SSL_CIPHER_LIST, implode(':', $supportedCiphers));`

On localhost, curl is using GnuTLS/3.4.10 and on the server curl is using NSS/3.36. I think the `$supportedCiphers` array is specified to work with OpenSSL and not with NSS. Cipher suite names for NSS and OpenSSL can be found here: [https://www.openssl.org/docs/manmaster/man1/ciphers.html](https://www.openssl.org/docs/manmaster/man1/ciphers.html)

Will it be safe to just remove these lines?

**Comment by oldpec** [comment]
The latest version of the SDK should have the bits you are referring to removed already, since:

https://github.com/globalpayments/php-sdk/commit/dfbf49411a08d43c1f0953beeb23f16e38009ef2

**Comment by alecogt** [comment]
Thank you @oldpec. I have updated to version 1.2.1 and the error has been fixed.
