### ISSUE TITLE
$language parameter is missing in the ServicesConfig class

### ISSUE THREAD

**Issue by mcspronko** [globalpayments/php-sdk#17]
Configuration used 
```php
        $servicesConfig = new ServicesConfig();
        $servicesConfig->merchantId = $this->config->getMerchantId();
        $servicesConfig->accountId = $this->config->getAccountId();
        $servicesConfig->sharedSecret = $this->config->getSharedSecret();
        $servicesConfig->serviceUrl = $this->config->getServiceUrl();

        $hostedPaymentConfig = new HostedPaymentConfig();
        $hostedPaymentConfig->setVersion(HppVersion::VERSION_2);
        $hostedPaymentConfig->setLanguage('en');

        $servicesConfig->hostedPaymentConfig = $servicesConfig;
```

## Expected Result
Realex Connector works as per design.

## Actual Result
```
Notice: Undefined property: GlobalPayments\Api\ServicesConfig::$language in /Users/pronko/www/projects/magento23/vendor/globalpayments/php-sdk/src/Gateways/RealexConnector.php on line 521
```

When I add language to the ServicesConfig, the error disappears, but the new one is shown.

```
$servicesConfig->language = 'en';
```

**Comment by eric-vest** [comment]
Hi Max,

A cursory glance at the SDK shows language as a property of HostedPaymentConfig as well as the setLanguage function and is being retrieved in the RealexConnector from that same object [here](https://github.com/globalpayments/php-sdk/blob/617001d9d3c22707e7758d503cb007474854e6f7/src/Gateways/RealexConnector.php#L543).

I see the error you get when you try to set language on ServicesConfig, what error do you get when you use setLanguage to set the language on the HostedPaymentConfig?

**Comment by mcspronko** [comment]
Hi @eric-vest, in theory yes, clicking through SDK explains how the language should be set, but in reality, as I wrote, setLanguage() method sets language to the HostedPaymentConfig, but in SDK the RealexConnector class during the execution uses ServicesConfig config.

So, the error with language I get is when i use "the proper way of setting and using setLanguage", but error disappears when i set language dynamically to the ServicesConfig class.

I use xDebug for debugging :).

**Comment by eric-vest** [comment]
Okay, I'm with you.  Thanks for the info.  I'll let you know when we get that sorted out.

**Comment by mcspronko** [comment]
Thank you @eric-vest

**Comment by mcspronko** [comment]
I found the issue, it was my mistake, I've accidentally assigned servicesConfig to the hostedPaymentConfig.

    $servicesConfig->hostedPaymentConfig = $servicesConfig;

There is no issue.
