### ISSUE TITLE
Payments not working due to "ambiguous class resolution" 

### ISSUE THREAD

**Issue by fatonsopa** [globalpayments/php-sdk#19]
Payments are unable to be because of the following error:

![image](https://user-images.githubusercontent.com/9337943/58952575-5a376480-8794-11e9-881a-2e0c6f779561.png)

This is caused because there are 2 files that use the same namespace & class name, and composer autoloading the first one, which happend to be the wrong one:

<pre>
<code>
'GlobalPayments\\Api\\Entities\\Enums\\TransactionType' => $vendorDir . '/globalpayments/php-sdk/src/Entities/Enums/TimeZoneConversion.php',
</code>
</pre>

instead of this
<pre>
<code>
'GlobalPayments\\Api\\Entities\\Enums\\TransactionType' => $vendorDir . '/globalpayments/php-sdk/src/Entities/Enums/TransactionType.php',
</code>
</pre>

![image](https://user-images.githubusercontent.com/9337943/58952387-d9786880-8793-11e9-9c52-4ea856ef90c0.png)

I tried to clear composer caches, remove & reinstall the package but didn't solve the issue.

Please fix the following issue ASAP as our project is unable to be deployed to production due to this error.

Thank you,
Faton

**Comment by eric-vest** [comment]
Hi Faton,

We'll have this fixed and pushed out by mid-day tomorrow.  Thank you for bringing up this issue!

**Comment by eric-vest** [comment]
Hi Faton,

I just pushed out an update.  Get the latest code and let me know if you have any issues.
