### ISSUE TITLE
3D Secure v2 Support

### ISSUE THREAD

**Issue by samuel27m** [globalpayments/php-sdk#20]
When is 3D Secure v2 Support through the SDK coming out?

With the July deadline to implement this, not having the SDK ready is a huge setback for developers.

**Comment by Brucimus83** [comment]
+1 I am waiting for the update to complete my companies 3ds 2 upgrade, and this is holding me back.

**Comment by samuel27m** [comment]
@Brucimus83 best option would be to use their HPP solution ... I don't think they will be updating the SDK any time soon

**Comment by craigcarnell** [comment]
They have stated early August.

**Comment by craigcarnell** [comment]
This is now released in 1.3.0
