### ISSUE TITLE
POST https://api.heartlandportico.com/SecureSubmit.v1/api/token? 403 (Forbidden)

### ISSUE THREAD

**Issue by sunnykasera3107** [globalpayments/php-sdk#21]
Hello,

Trying to integrate it on a tours website. But it always throws 403 error. 
I have followed all steps as mentioned on the documentation here https://developer.heartlandpaymentsystems.com/Ecommerce/Card

Could you please help me?

Thanks

**Comment by slogsdon** [comment]
Hi @sunnykasera3107,

Are you using a valid public API key during the single-use tokenization request? The endpoint you're hitting is in our production environment, so a valid public API key for a production account should be used in the request.

**Comment by sunnykasera3107** [comment]
Hi @slogsdon,
Thanks for the help. It solved my query. Now I am good to use it. It was a system error, My system was not rendering API key in the template which caused this issue.

Many Thanks
Sunny
