### ISSUE TITLE
AVS Address response

### ISSUE THREAD

**Issue by craigcarnell** [globalpayments/php-sdk#22]
vendor/globalpayments/php-sdk/src/Entities/Transaction.php

```
public $avsResponseCode;
public $avsResponseMessage;
public $avsAddressResponse;
```

Which one should would be using for avsAddress and avsPostcode address matching e.g. 'M' etc.?

**Comment by hpsTony** [comment]
Use $avsResponseCode to obtain the letter value for AVS responses like "M" or "Z". 

You can test this in our certification gateway by processing test sales for specific dollar amounts. If you'd like to do so, run a test sale for $90.01 and you should see "A" returned for $avsResponseCode.

**Comment by craigcarnell** [comment]
@hpsTony For realex, I may be wrong, but there should be one value for post code match and one value for address match?

**Comment by craigcarnell** [comment]
Answered my own question from the website, not the code..

// get the result of the AVS check
    $avsPostCodeCheck = $response->avsResponseCode; // M = Matched
    $avsAddressLineCheck->avsAddressResponse; // M = Matched
