### ISSUE TITLE
Get  payload of the sent request

### ISSUE THREAD

**Issue by zgbetancur** [globalpayments/php-sdk#26]
there is no way to get the raw payload (XML or JSON) of the sent request. 
This is really useful for testing and debugging purposes.
Could be great to have the raw answer received from the service.

**Comment by mike-brookes** [comment]
https://github.com/globalpayments/php-sdk/blob/master/src/Gateways/RealexConnector.php
Line 467 for a charge request
Line 759 for 3DSecure
Line 864 for Recurring
You will just need to print (to error log or screen whichever suits) the saveXML data.
To do the same with the response you can just print the response variable.
I hope this helps!
