### ISSUE TITLE
Process HPP Response, incorrect hash

### ISSUE THREAD

**Issue by b0gucki3** [globalpayments/php-sdk#3]
Hi,

The HPP redirects to `responseEndpoint` link with $_POST containing `hppResponse` JSON. That's all good.

When processing the HPP Response (following this guide https://developer.realexpayments.com/#!/ecommerce/card-payments/hpp#card-payments-hpp-process-response) the SDK throws an exception on the server side "Incorrect hash. Please check your code and the Developers Documentation.".

`$parsedResponse = $service->parseResponse($_POST['hppResponse'], false);` or
`$parsedResponse = $service->parseResponse($_POST['hppResponse'], true);`

I'm using sandbox account. Note that the transactions are successfully processed and visible in the back-end of Realex.

I've tested it on another host using HTTPS, same issue. I made sure that the `merchantId`, `accountId` and `secret` are correct.

Thanks

**Comment by loony383** [comment]
Don't use the $_POST['hppResponse'] values directly. I found that I needed to base64_decode the values 1st to be able to pass this hash check.
