### ISSUE TITLE
How to implement Debit card purchase?

### ISSUE THREAD

**Issue by fullstact69** [globalpayments/php-sdk#51]
I'd like to purchase with Debit Card using Globalpayment api at php. How can I implement this?

**Comment by MSmedal** [comment]
Hi @fullstact69 , are you trying to implement pin debit (with some sort of hardware integration) or is the goal to be able to accept debit cards and payment cards in general? Would you mind replying to my team's email at: developers@heartland.us ?

**Comment by fullstact69** [comment]
I used debit card number and expired date like credit card. And also there is a problem to purchase using credit card.

"Unexpected Gateway Response: 108 - Using test system. Please use pre-approved test cards ONLY"
1 - How can I use debit card number and expired date?
2 - How can I make production system for real credit card?

**Comment by MMasterson** [comment]
@fullstact69 it sounds like you're using test keys here. Did you talk with global and get production key values? Test card numbers should have been provided in your test scripts.

**Comment by seanmacdomhnall-gp** [comment]
@fullstact69 that error message indicates you are using the Global Payments Ecommerce gateway.

1. Test cards are available here: https://developer.globalpay.com/resources/test-card-numbers
2. In order for your account to be set live you'll need to engage with our support team.

As my colleague @MSmedal mentioned above, if you could please reply to our team's email at developers@heartland.us
