### ISSUE TITLE
I cannot use PHP-sdk

### ISSUE THREAD

**Issue by Marvin261** [globalpayments/php-sdk#52]
Hello. I am Marvin. I am a website developer. I am interested to try globalpayments hpp payments. But I am having trouble finding the php-sdk file "autoload.php" or "init.php". I am directly downloaded php sdk file.

Please help me as soon as possible so that I can continue my work.

Regards,
Marvin.

**Comment by Marvin261** [comment]
For now I manually use php require  to load php file like this: 

<?php
/** GlobalPayments PHP-SDK-2.0.5 Initialize Charge Payment directory file */

require(dirname(__FILE__) . '/src/Entities/Exceptions/ApiException.php');
require(dirname(__FILE__) . '/src/Entities/Exceptions/ArgumentException.php');

require(dirname(__FILE__) . '/src/ServicesConfig.php');
require(dirname(__FILE__) . '/src/Entities/Enum.php');
require(dirname(__FILE__) . '/src/Entities/Enums/Environment.php');

require(dirname(__FILE__) . '/src/ServicesContainer.php');
require(dirname(__FILE__) . '/src/Entities/Enums/TransactionType.php');
require(dirname(__FILE__) . '/src/Entities/Enums/TransactionModifier.php');
require(dirname(__FILE__) . '/src/Builders/BaseBuilder/ValidationClause.php');
require(dirname(__FILE__) . '/src/Builders/BaseBuilder/ValidationTarget.php');
require(dirname(__FILE__) . '/src/Builders/BaseBuilder/Validations.php');
require(dirname(__FILE__) . '/src/Builders/BaseBuilder.php');
require(dirname(__FILE__) . '/src/Builders/TransactionBuilder.php');
require(dirname(__FILE__) . '/src/Builders/ManagementBuilder.php');
require(dirname(__FILE__) . '/src/Entities/Transaction.php');
require(dirname(__FILE__) . '/src/Entities/Enums/PaymentMethodType.php');
require(dirname(__FILE__) . '/src/PaymentMethods/Interfaces/IPaymentMethod.php');
require(dirname(__FILE__) . '/src/PaymentMethods/TransactionReference.php');
require(dirname(__FILE__) . '/src/Utils/GenerationUtils.php');
require(dirname(__FILE__) . '/src/Services/HostedService.php');

require(dirname(__FILE__) . '/src/Entities/Enums/Secure3dVersion.php');
require(dirname(__FILE__) . '/src/Gateways/IRecurringService.php');
require(dirname(__FILE__) . '/src/Gateways/ISecure3dProvider.php');
require(dirname(__FILE__) . '/src/Gateways/IPaymentGateway.php');
require(dirname(__FILE__) . '/src/Gateways/GatewayResponse.php');
require(dirname(__FILE__) . '/src/Gateways/Gateway.php');
require(dirname(__FILE__) . '/src/Gateways/XmlGateway.php');
require(dirname(__FILE__) . '/src/Entities/Exceptions/GatewayException.php');
require(dirname(__FILE__) . '/src/Gateways/RealexConnector.php');
?>

**Comment by MSmedal** [comment]
Hi again Marvin,
Composer is definitely the [easiest way to get going with our PHP SDK](https://github.com/globalpayments/php-sdk#installation) since it handles the PSR-4 Autoloader requirements of our SDK.

**Comment by Marvin261** [comment]
Thanks for information. I do not use composer. I will close this thread now.
