### ISSUE TITLE
Issue in AuthorizationBuilder

### ISSUE THREAD

**Issue by jeyserEssedi** [globalpayments/php-sdk#57]
Hi, i have a issue in your sdk 

_**Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "UnsupportedTransactionException" from namespace "GlobalPayments\Api\Builders". Did you forget a "use" statement for another namespace? in /app/vendor/globalpayments/php-sdk/src/Builders/AuthorizationBuilder.php:502**_

I tried to catch this exception, but fail

```
catch (UnsupportedTransactionException $e) {
                $paymentResponse
                    ->setIsSuccess(false)
                    ->setErrorCode($e->getCode())
                    ->setData($e->getMessage());

                return $paymentResponse;
```

**Comment by Davvers84** [comment]
I am having the same issue.

1) Tests\Unit\GlobalPayTest::validate_hosted_payment_data
Error: Class 'GlobalPayments\Api\Builders\UnsupportedTransactionException' not found

**/var/www/dashboard/vendor/globalpayments/php-sdk/src/Builders/AuthorizationBuilder.php:502**
/var/www/dashboard/app/GlobalPay.php:40
/var/www/dashboard/tests/Unit/GlobalPayTest.php:30

**Comment by jeyserEssedi** [comment]
Solved by pull request, waiting to include in next release. Anyway in my case i change a litle thing

Before:
 ```
$config = new ServicesConfig();
```
After:
```
$config = new ServicesConfig();
$config->gatewayProvider = GatewayProvider::GP_ECOM;
```

By default ServicesConfig initialize with gateway Portico, and this gateway dont support HPP, here is the origin of the UnsupportedTransactionException

**Comment by Davvers84** [comment]
@jeyserEssedi your pull request doesn't include the fix above it just adds the declartion in the Auth builder i.e.

`use GlobalPayments\Api\Entities\Exceptions\UnsupportedTransactionException`

Or have I missed something?

**Comment by jeyserEssedi** [comment]
Solve that there is no error in that case, my previous suggestion is part of the logic of my code, which I have modified so that this exception will not be thrown at me.


```
public function serialize()
    {
        $this->transactionModifier = TransactionModifier::HOSTEDREQUEST;
        parent::execute();

        $client = ServicesContainer::instance()->getClient();

        if ($client->supportsHostedPayments()) {
            return $client->serializeRequest($this);
        }
        throw new UnsupportedTransactionException("Your current gateway does not support hosted payments.");
    }
```

at this point my code did not work because the default gateway does not support HPP, so it threw the exception, but it gave an error because it was not included.
