### ISSUE TITLE
Which one is actively developed?

### ISSUE THREAD

**Issue by craigcarnell** [globalpayments/php-sdk#6]
This or https://github.com/realexpayments/rxp-remote-php ?

**Comment by rxp-developers** [comment]
@craigcarnell 

Thanks for your question. This is the actively developed SDK, inasmuch as we'll be adding new features to this one. The Realex branded ones we'll continue to support from a security perspective etc. but no new features as such will be added.

So it will be this SDK that supports 3D Secure 2.

**Comment by craigcarnell** [comment]
@rxp-developers do you have an ETA when it will be updated to support 3dsecurev2?

**Comment by stephenharris** [comment]
@rxp-developers - sorry to nudge but is there an ETA for 3D Secure 2?
