### ISSUE TITLE
Sample API auth code giving 'Secure 3d is not configured on the connector' 

### ISSUE THREAD

**Issue by footfish** [globalpayments/php-sdk#71]
Code from api reference (https://developer.globalpay.com/api/3d-secure-two#3ds2-initiate) gives 'Secure 3d is not configured on the connector.' 

Error because  TWO is an undefined index in php-sdk/src/ServicesContainer.php (line 174), function getSecure3d(). 
I'm using fresh clone of repo. 
```
> php authenticate.php
Failure: Secure 3d is not configured on the connector.

> php -v
PHP 7.2.24 (cli) (built: Oct 22 2019 08:28:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```
authenticate.php
```
<?php
require_once('/var/www/html/vendor/autoload.php');

use GlobalPayments\Api\ServiceConfigs\Gateways\GpEcomConfig;
use GlobalPayments\Api\ServicesContainer;
use GlobalPayments\Api\Services\Secure3dService;
use GlobalPayments\Api\PaymentMethods\CreditCardData;
use GlobalPayments\Api\Entities\Enums\Secure3dVersion;
use GlobalPayments\Api\Entities\Exceptions\ApiException;
use GlobalPayments\Api\Entities\Enums\ColorDepth;
use GlobalPayments\Api\Entities\ThreeDSecure;
use GlobalPayments\Api\Entities\Address;
use GlobalPayments\Api\Entities\BrowserData;
use GlobalPayments\Api\Entities\Enums\AddressType;
use GlobalPayments\Api\Entities\Enums\ChallengeWindowSize;
use GlobalPayments\Api\Entities\Enums\MethodUrlCompletion;

// configure client & request settings
$config = new GpEcomConfig();
$config->merchantId = 'myMerchantId';
$config->accountId = 'ecom3ds';
$config->sharedSecret = 'secret';
$config->methodNotificationUrl = "https://www.example.com/methodNotificationUrl";
$config->challengeNotificationUrl = "https://www.example.com/challengeNotificationUrl";
$config->merchantContactUrl = "https://www.example.com/about";
$config->secure3dVersion = Secure3dVersion::TWO;
ServicesContainer::configureService($config);

// Add the cardholder data
$card = new CreditCardData();
$card->number = "4012001038488884";
$card->expMonth = "05";
$card->expYear = "25";
$card->cvn = "123";
$card->cardHolderName = "James Mason";

// Add the customer's billing address
$billingAddress = new Address();
$billingAddress->streetAddress1 = "Apartment 852";
$billingAddress->streetAddress2 = "Complex 741";
$billingAddress->streetAddress3 = "Unit 4";
$billingAddress->city = "Chicago";
$billingAddress->state = "IL";
$billingAddress->postalCode = "50001";
$billingAddress->countryCode = "840";

// Add the customer's shipping address
$shippingAddress = new Address();
$shippingAddress->streetAddress1 = "Flat 456";
$shippingAddress->streetAddress2 = "House 789";
$shippingAddress->streetAddress3 = "Basement Flat";
$shippingAddress->city = "Halifax";
$shippingAddress->postalCode = "W5 9HR";
$shippingAddress->countryCode = "826";

// Add captured browser data from the client-side and server-side
$browserData = new BrowserData();
$browserData->acceptHeader = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8";
$browserData->colorDepth = ColorDepth::TWENTY_FOUR_BITS;
$browserData->ipAddress = "123.123.123.123";
$browserData->javaEnabled = TRUE;
$browserData->language = "en";
$browserData->screenHeight = "1080";
$browserData->screenWidth = "1920";
$browserData->challengWindowSize = ChallengeWindowSize::FULL_SCREEN;
$browserData->timeZone = "0";
$browserData->userAgent = "Mozilla/5.0 (Windows NT 6.1; Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36";

$threeDSecureData = new ThreeDSecure();
$threeDSecureData->serverTransactionId = "9de5bccf-c438-4024-8961-ec4b3cff15ff";
$threeDSecureData->serverTransactionId = "af65c369-59b9-4f8d-b2f6-7d7d5f5c69d5";

try {
   $threeDSecureData = Secure3dService::initiateAuthentication($card, $threeDSecureData)
      ->withAmount(10.01)
      ->withCurrency("USD")
      ->withOrderCreateDate(date("Y-m-d H:i:s"))
      ->withCustomerEmail("james.mason@example.com")
      ->withAddress($billingAddress, AddressType::BILLING)
      ->withAddress($shippingAddress, AddressType::SHIPPING)
      ->withBrowserData($browserData)
      ->withMethodUrlCompletion(MethodUrlCompletion::YES)
      ->withMobileNumber("44", "7123456789")
      ->execute(Secure3dVersion::TWO);
} catch (ApiException $e) {
        echo 'Failure: ' . $e->getMessage()."\n";
        exit;
   // TODO: add your error handling here
}

$status = $threeDSecureData->status;

```

**Comment by liamdv4** [comment]
I think you've hit an issue that cost me a fair few hours recently. Somewhere between SDK 2.1.x and 2.2.x that execute() method acquired an additional in a way that breaks code that worked for 2.1 (including our own test framework here). We were getting errors similar to the one you're getting here. I haven't found any documentation (or had time to look properly) as to what this change was about but from the test scripts, I discovered that adding 'default' as the first parameter does the trick, e.g.

$secureEcom = Secure3dService::checkEnrollment($this->card)
                                                ->execute('default', Secure3dVersion::TWO);

I hope this works for you. It's a real pity there isn't a community forum where those of us struggling with these things could work together.

**Comment by footfish** [comment]
@liamdv4 Great, good pointer. I see in php-sdk/src/Services/Secure3dService.php the function has added the argument for initiateAuthentication too, so I think you're correct (although argument has not been added for initiateAuthentication  in tests, I had assumed they would be the reference to check against). 

```
  public static function initiateAuthentication(IPaymentMethod $paymentMethod, ThreeDSecure $secureEcom)
    {
```
I gave it a quick try and now get a  'Status Code: 400 -', which looks like a better fault (probably some of the default params) I'll re-check tomorrow when I have time.

**Comment by footfish** [comment]
@securesubmit-buildmaster  @liamdv4  Confirming the solution is to add 'default' as the first argument to the initiateAuthentication->execute. This should be corrected on example code (https://developer.globalpay.com/api/3d-secure-two#3ds2-initiate) and test cases. 

```
   $threeDSecureData = Secure3dService::initiateAuthentication($card, $threeDSecureData)
      ->withAmount(10.01)
      ->withCurrency("USD")
      ->withOrderCreateDate(date("Y-m-d H:i:s"))
      ->withCustomerEmail("james.mason@example.com")
      ->withAddress($billingAddress, AddressType::BILLING)
      ->withAddress($shippingAddress, AddressType::SHIPPING)
      ->withBrowserData($browserData)
      ->withMethodUrlCompletion(MethodUrlCompletion::YES)
      ->withMobileNumber("44", "7123456789")
      ->execute('default',Secure3dVersion::TWO);            // ** Make sure to add 'default' as first argument here 
```

Note also that using the example code will return a 'Status Code: 400 -' because the 'serverTransactionId' must be an 'issued' one (As an aside to endpoint developers, I don't think this is a good way to handle invalid an 'serverTransactionId' on a test endpoint. Some further cause information would have been nice'.)

**Comment by irishtarot** [comment]
Hi there. I have the very same problem and I am getting the same Status Code: 400 when using the execute('default',Secure3dVersion::TWO) method signature so the developer guide must definitely be wrong with execute(Secure3dVersion::TWO)

I still haven't managed to get it working, would anybody have a fixed code above that works as I am stumped and the deadline for using SCA 3D2 is like two days from now.

Thanks all and happy new year.
David

**Comment by irishpilot** [comment]
Hi there. I have the very same problem and I am getting the same Status Code: 400 when using the execute('default',Secure3dVersion::TWO) method signature so the developer guide must definitely be wrong with execute(Secure3dVersion::TWO)

I still haven't managed to get it working, would anybody have a fixed code above that works as I am stumped and the deadline for using SCA 3D2 is like two days from now.

Thanks all and happy new year.
David

**Comment by liamdv4** [comment]
Hi David,

Are you sure that the sandbox account you're using has 3DSv2 enabled? At least with the old Realex accounts this was something that you had to request. For example, our original sandbox account was called "internet" and Realex support created a second one for us called "internet3ds". I think it's another one of those peculiarities that's not documented or mentioned in the developer docs.

Best of luck.

Liam

**Comment by irishpilot** [comment]
Hi Liam, thanks for having a look for me. I think it should be as they set up a test account for me for testing the migration before moving the production over but I'll call them tomorrow when the open to check to be sure.

It is a tough one as I assume everyone else who is having to quickly move over to 3D 2 must be facing the same issues with the docs which is why I posted here. I think once I work it out I will write up a doc on exactly how to get it working as I'm finding it really a nightmare.

Thanks
David

**Comment by footfish** [comment]
@irishpilot see my comment regarding Status Code: 400. The 'serverTransactionId' must be a valid one (ie. issued during version check). If you use the values set in sample code (like $threeDSecureData->serverTransactionId = "af65c369-59b9-4f8d-b2f6-7d7d5f5c69d5";) then you will get a Status Code: 400.
