### ISSUE TITLE
directPost example on developer site is incomplete.

### ISSUE THREAD

**Issue by PremiumHelp** [globalpayments/php-sdk#72]
Hi, There is no clear details on [1] how to create with [2] what format the following parameter when implementing Direct Post.
TIMESTAMP
MERCHANT_ID
ACCOUNT
ORDER_ID
AMOUNT
CURRENCY
SHA1HASH
AUTO_SETTLE_FLAG
HPP_VERSION
HPP_POST_DIMENSIONS
HPP_POST_RESPONSE
MERCHANT_RESPONSE_URL

No clear instruction on this.

[developer.heartlandpaymentsystems.com](url) completely differs than

[developer.globalpay.com](url)

Please help me out.

**Comment by MSmedal** [comment]
Sorry for the delayed reply @PremiumHelp. 

The two portals you linked to cover integrations for separate payment gateways under the Global Payments umbrella. This SDK wraps both of them, but usage will of course vary depending on which gateway(s) you're connecting to. For GP's Direct Post solution you can find those examples and insights [here](https://developer.globalpay.com/ecommerce/direct-post#direct-post).
