### ISSUE TITLE
missing argument for the function getRecurringClient

### ISSUE THREAD

**Issue by talkalanee** [globalpayments/php-sdk#73]
the function getRecurringClient need one argument ($configName) in https://github.com/globalpayments/php-sdk/blob/5cf1b512408cf537a279c1d7ba943409e1a8584d/src/PaymentMethods/RecurringPaymentMethod.php#L246

because there are no default value in the function declaration: https://github.com/globalpayments/php-sdk/blob/5cf1b512408cf537a279c1d7ba943409e1a8584d/src/ServicesContainer.php#L124

**Comment by MSmedal** [comment]
Thanks for bringing this to our attention @talkalanee. At first glance it might make sense for us to remove the entire switch because using a default value may cause issues in cases of integrations that use multiple gateway configs. Either way we'll try to have this resolved soon.

**Comment by MSmedal** [comment]
Thanks again @talkalanee for pointing this out. This should be resolved as of the latest release, 2.2.3
