### ISSUE TITLE
ServicesConfig.php does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by legitalk** [globalpayments/php-sdk#76]
Composer version 2 is showing this when running `composer update`:

Class GlobalPayments\Api\ServiceConfigs\ServicesConfig located in ./vendor/globalpayments/php-sdk/src/ServicesConfig.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by MSmedal** [comment]
Hello!

Thanks for pointing this out. I see the culprit and will have this fixed soon.

For my edification, can you tell me what version of Composer you're on? I wasn't able to reproduce the message with 2.0.8

**Comment by legitalk** [comment]
Composer version 2.0.8 2020-12-03 17:20:38

**Comment by MSmedal** [comment]
Again, thanks for the info. This should be resolved as of the release this morning - tagged version 2.2.3

**Comment by legitalk** [comment]
Thank you, now its fine without that message.
