### ISSUE TITLE
Bug: preg_match(): No ending delimiter '^' found

### ISSUE THREAD

**Issue by talkalanee** [globalpayments/php-sdk#78]
I have the error: preg_match(): No ending delimiter '^' found, because there are a missing delimiter for the last regex in the array $cardTypes

https://github.com/globalpayments/php-sdk/blob/f86b37e77e01f467af7c63a8acde110783d0ffb1/src/Utils/CardUtils.php#L53

**Comment by MSmedal** [comment]
@talkalanee , I see what you mean. It looks like it should be "Wex" => "**/**^(?:690046|707138)**/**" instead. Thanks for pointing this out!

**Comment by talkalanee** [comment]
Exactly! 
You're welcome :)
