### ISSUE TITLE
 The specified configuration has not been configured for gateway processing.

### ISSUE THREAD

**Issue by martinnoblehouse** [globalpayments/php-sdk#82]
Getting the following exception when testing:

GlobalPayments\Api\Entities\Exceptions\ApiException Object
(
    [message:protected] => The specified configuration has not been configured for gateway processing.
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /home/mrsblooms/vendor/globalpayments/php-sdk/src/ServicesContainer.php
    [line:protected] => 102
    [trace:Exception:private] => Array
    )

**Comment by JohnnyLufa** [comment]
Try this, but replace GpEcommConfig with the Gateway provider's config that you use. (if you are using another one)
```
use GlobalPayments\Api\ServiceConfigs\Gateways\GpEcomConfig;
use GlobalPayments\Api\ServiceConfigs\ServicesConfig;

...

$config = new GpEcomConfig();
$config->merchantId = $yourMerchantId
$config->accountId = $yourAccountId
$config->sharedSecret = $yourSharedSecret
$config->serviceUrl = $yourServiceUrl
$svcConfig = new ServicesConfig();
$svcConfig->gatewayConfig = $config;
ServicesContainer::configure($svcConfig);
```

**Comment by CristinaNechitaGP** [comment]
Starting with version 2.1.0: 
```
use GlobalPayments\Api\ServiceConfigs\Gateways\GpEcomConfig;
use GlobalPayments\Api\ServicesContainer;

...

$config = new GpEcomConfig();
$config->merchantId = $yourMerchantId
$config->accountId = $yourAccountId
$config->sharedSecret = $yourSharedSecret
$config->serviceUrl = $yourServiceUrl
ServicesContainer::configureService($config);
```
