### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'GlobalPayments\Api\Gateways\LodgingData' not found in /var/www/load_management/vendor/globalpayments/php-sdk/src/Gateways/PorticoConnector.php:1461 

### ISSUE THREAD

**Issue by riyaas** [globalpayments/php-sdk#83]
This issue happens while calling ReportingService::findTransactions()  withStartDate and withEndDate
Example

    $dateFormat = 'Y-m-d\TH:i:s.00\Z';
    $dateMinus10 = new \DateTime();
    $dateMinus10->sub(new \DateInterval('P60D'));
    $dateMinus10Utc = gmdate($dateFormat, $dateMinus10->format('U'));
    $nowUtc = gmdate($dateFormat);

     $resp = ReportingService::findTransactions()
            ->withStartDate($dateMinus10Utc)
            ->withEndDate($nowUtc)
            ->execute();
Tested the code with version 2.2.8

This can be resolved by adding below line to "globalpayments/php-sdk/src/Gateways/PorticoConnector.php"

"use GlobalPayments\Api\Entities\Reporting\LodgingData;"

**Comment by cristina-nechita** [comment]
This was fixed in 2.2.10.
