### ISSUE TITLE
Logger for 3-DS

### ISSUE THREAD

**Issue by gitHusband** [globalpayments/php-sdk#86]
Hey, 

I want to get the original request data and response data, http code, curl code etc when I send a 3-DS request.

Please see https://developer.globalpay.com/api/3d-secure-two#3ds2-obtain

But I had found no way.

I know php-sdk support RequestLogger function. So I think I can use this function to set/get the original request data and response data.

Unfortunately, 3-DS GATEWAY does not support the RequestLogger. See GlobalPayments\Api\ServiceConfigs\Gateways\GpEcomConfig->configureContainer

Please can you update the code to support this function, thanks!

**Comment by cristina-nechita** [comment]
The RequestLogger on Gp3DSProvider is available starting with version 2.3.4 .
