### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by kirilow** [globalpayments/php-sdk#95]
I am new to using globalpayments.
So far I have used other systems like stripe.
In the implementation of HPP, is there such a thing as WEBHOOK, ie. if a successful or unsuccessful payment is made, OUR system will send the payment data to my special URL and, if is possible, how to configure it.
I use php-sdk.

**Comment by securesubmit-buildmaster** [comment]
We do not have WEBHOOKS within the SDKs themselves, but the SDK will raise an exception when the payment is unsuccessful and you can handle this in any manner you desire.
